
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 6
#define YY_END_OF_BUFFER 7
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[626] =
    {   0,
        0,    0,    7,    5,    4,    3,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        0,    4,    4,    4,    4,    4,    4,    2,    4,    4,
        3,    4,    4,    1,    3,    2,    2,    4,    4,    4,
        4,    4,    4,    3,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        0,    4,    4,    4,    4,    4,    4,    2,    4,    4,
        4,    4,    4,    3,    4,    4,    4,    2,    4,    4,
        2,    4,    4,    4,    4,    4,    4,    4,    2,    4,

        3,    2,    4,    3,    4,    4,    1,    4,    4,    2,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    1,    4,
        4,    2,    4,    4,    4,    3,    4,    4,    4,    2,
        4,    3,    2,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    2,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    1,    4,    4,    4,    4,

        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    2,    1,    4,    4,    4,    4,    2,    4,
        4,    4,    4,    4,    4,    4,    0,    4,    4,    4,
        2,    2,    4,    4,    4,    4,    4,    4,    4,    4,
        0,    4,    4,    4,    4,    3,    4,    4,    4,    4,
        4,    4,    2,    4,    3,    0,    4,    4,    4,    4,
        4,    3,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    0,
        4,    4,    4,    4,    4,    4,    4,    4,    2,    2,

        0,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    2,    4,    4,
        4,    4,    2,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    3,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    0,    4,    4,    4,    4,    4,    4,    0,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        0,    4,    4,    4,    4,    4,    4,    0,    4,    4,

        4,    4,    2,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    0,    3,    4,    4,    4,
        4,    4,    4,    0,    0,    0,    4,    4,    4,    4,
        4,    4,    2,    2,    3,    4,    4,    4,    4,    0,
        4,    4,    4,    4,    4,    4,    4,    4,    3,    4,
        4,    3,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    2,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    0,    4,    4,    0,    4,    4,    4,    4,

        4,    4,    4,    4,    4,    4,    4,    0,    0,    3,
        4,    4,    4,    4,    4,    4,    4,    4,    0,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    3,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    0,    4,
        0,    4,    4,    4,    4,    4,    3,    0,    0,    4,
        4,    4,    2,    4,    0,    4,    4,    4,    4,    0,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    0,
        4,    0,    4,    4,    3,    4,    4,    4,    4,    4,
        4,    0,    4,    4,    4,    4,    4,    4,    0,    4,

        0,    4,    4,    4,    4,    0,    4,    4,    4,    4,
        0,    4,    4,    0,    4,    4,    0,    4,    4,    0,
        4,    0,    4,    4,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        1,    1,    1,    1,    1,    1,    6,    7,    8,    9,

       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[32] =
    {   0,
        1,    1,    2,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3
    } ;

static const flex_int16_t yy_base[628] =
    {   0,
        0,    0, 1440, 1441, 1436,   29,   58,   86,  110,  134,
      161,  182,  206,   63,   59,   64,  230,  248,  276,  300,
      328,   60,  351,  375,  399,  423,  444,  462,  483,   70,
        0, 1435,   74,   90,   82,   77,   88,  112,  101,  114,
      122,  116,  135,  126,  132, 1434,   62,  145,  507,  147,
      124,   80,  140,  113,  156,  138,   76,  157,  153,  159,
      166,  167,  174,  177,  176,  183,  187,  197,  200,  195,
     1427,  216,  218,  207,  219,  208,  196,  535,  242,  235,
      227,  561,  243,  266,  238,  246,  260,   30,  171,  245,
      257,  264,  224,  285,  267,  284,  286,  295,  272,  281,

      297,  329,  334,  304,  345,  307, 1432,  322,  261,  302,
      352,  340,  306,  332,  333,  347,  359,  361,  366,  371,
      367,  379,  394,  372,  397,  590,  418,  270,  395,  390,
      382,  405,  419,  428,  442,  437,  401,  408,  426,  445,
      452,  450,  440,  463,  475,  459,  471,  477,  468,  614,
      425,  476,  453,  492,  491,  493,  484,  389,  502,  498,
     1441,  503,  516,  505,  513,  522,  524,  532,  537,  533,
      520,  538,  546,  547,  551,  550,  552,  553,  558,  559,
      562,  567,  572,  574,  565,  575,  577,  580,  579,  597,
      587,  578,  584,  588,  602, 1431,  608,  605,  606,  616,

      618,  619,  623,  620,  622,  624,  627,  625,  638,  626,
      628,  642,  643,  646,  647, 1427,  648,  649,  651,  654,
      657,  655,  659,  660,  663,  667, 1419,  668,  670,  671,
      672,  582,  673,  674,  675,  680,  681,  683,  684,  688,
     1422,  687,  694,  695,  697,  696,  700,  704,  705,  706,
      707,  711,  710,  715, 1427, 1409,  714,  716,  720,  718,
      721,  719,  722,  724,  726,  731,  744,  730,  745,  732,
      746,  734,  747,  758,  748,  750,  762,  759,  761,  763,
      767,  770,  771,  772,  773,  776,  778,  779,  780, 1419,
      782,  786,  787,  789,  793,  791,  802,  792,  808,  810,

     1407,  794,  805,  812,  814,  815,  813,  817,  818,  819,
      821,  820,  831,  837,  833,  822,  827,  839,  841,  845,
      846,  857,  848,  850,  859,  853,  860,  861,  862,  865,
      867,  871,  872,  868,  879,  873,  874,  876,  885,  877,
      887,  890,  889,  893,  899,  900,  895,  901,  903,  907,
      908,  909,  913,  912,  918,  919,  920,  924,  926,  930,
      921,  927,  922,  935,  936,  941,  940,  942,  943,  945,
      946,  948, 1396,  949,  947,  951,  952,  950,  954, 1419,
      970,  955,  971,  960,  979,  981,  965,  969,  980,  985,
     1410,  986,  987,  989,  990,  991,  992, 1410,  993,  995,

      996,  997, 1419,  998, 1012,  999, 1000, 1001, 1014, 1015,
     1016, 1018, 1022, 1024, 1027, 1415, 1028, 1029, 1032, 1037,
     1033, 1038, 1039, 1395, 1394, 1405, 1040, 1043, 1049, 1042,
     1050, 1046, 1044, 1052, 1057, 1062, 1064, 1045, 1069, 1404,
     1067, 1071, 1073, 1075, 1078, 1082, 1083, 1079, 1084, 1086,
     1088, 1090, 1091, 1089, 1092, 1093, 1095, 1096, 1101, 1114,
     1097, 1116, 1117, 1121, 1102, 1107, 1125, 1126, 1129, 1130,
     1131, 1132, 1134, 1133, 1136, 1135, 1137, 1138, 1139, 1441,
     1140, 1156, 1143, 1154, 1158, 1160, 1161, 1164, 1162, 1168,
     1169, 1167, 1412, 1165, 1170, 1406, 1166, 1179, 1178, 1180,

     1187, 1181, 1183, 1191, 1196, 1198, 1195, 1390, 1387, 1197,
     1199, 1207, 1185, 1208, 1210, 1211, 1212, 1214, 1392, 1216,
     1217, 1220, 1218, 1219, 1222, 1225, 1223, 1224, 1236, 1235,
     1238, 1240, 1242, 1244, 1248, 1247, 1249, 1250, 1252, 1261,
     1262, 1263, 1264, 1265, 1266, 1267, 1268, 1269, 1402, 1271,
     1390, 1270, 1277, 1282, 1285, 1279, 1283, 1393, 1380, 1287,
     1296, 1298, 1299, 1288, 1382, 1301, 1302, 1297, 1309, 1390,
     1311, 1313, 1314, 1315, 1316, 1317, 1318, 1321, 1324, 1391,
     1320, 1379, 1319, 1327, 1322, 1334, 1328, 1332, 1342, 1344,
     1345,  819, 1346, 1347, 1350, 1351, 1352, 1358,  498, 1353,

      482, 1361, 1363, 1365, 1364,  405, 1366, 1368, 1369, 1374,
      356, 1376, 1378,  311, 1380, 1381,  195, 1382, 1383,  162,
     1384,   98, 1385, 1391, 1441, 1405,   71
    } ;

static const flex_int16_t yy_def[628] =
    {   0,
      625,    1,  625,  625,  626,  625,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,   23,   23,  626,
      627,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      627,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,

      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      625,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,

      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  625,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  625,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      625,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  625,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  625,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,

      625,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  625,  626,  626,  626,  626,  626,  626,  625,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      625,  626,  626,  626,  626,  626,  626,  625,  626,  626,

      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  625,  626,  626,  626,  626,
      626,  626,  626,  625,  625,  625,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  625,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  625,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  625,  626,  626,  625,  626,  626,  626,  626,

      626,  626,  626,  626,  626,  626,  626,  625,  625,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  625,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  626,  625,  626,
      625,  626,  626,  626,  626,  626,  626,  625,  625,  626,
      626,  626,  626,  626,  625,  626,  626,  626,  626,  625,
      626,  626,  626,  626,  626,  626,  626,  626,  626,  625,
      626,  625,  626,  626,  626,  626,  626,  626,  626,  626,
      626,  625,  626,  626,  626,  626,  626,  626,  625,  626,

      625,  626,  626,  626,  626,  625,  626,  626,  626,  626,
      625,  626,  626,  625,  626,  626,  625,  626,  626,  625,
      626,  625,  626,  626,    0,  625,  625
    } ;

static const flex_int16_t yy_nxt[1473] =
    {   0,
        4,    4,    4,    4,    5,    6,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,    5,   29,
       30,   31,   31,  241,   33,   34,   35,   32,   32,   36,
       37,   38,   32,   32,   32,   39,   40,   41,   32,   42,
       32,   43,   44,   45,   32,   32,   46,   32,   47,   32,
       31,   31,   31,   48,   31,   31,   31,   49,   86,   87,
       83,   46,   31,  161,   50,  158,   31,   51,   31,   31,
       52,   84,   31,   53,   31,  119,   46,   54,   31,  159,
       31,   85,   31,  168,  199,  162,  166,   46,   55,   56,

      160,  167,   46,   31,  165,   57,  171,  480,   58,  163,
      169,   59,   31,  164,   31,   31,   31,   46,   31,   60,
      172,  170,   46,  174,   31,  173,   31,  175,   31,   61,
      107,  177,   62,  176,   31,   63,   31,   31,  178,  182,
       31,  179,   31,   64,  184,   65,  180,   31,  195,   31,
      183,  185,  194,   46,  181,   31,   46,   46,   31,   31,
      198,   31,   66,   31,  196,  197,   67,  186,   31,   31,
      200,  622,  205,   31,   68,  201,   31,  203,   31,   31,
       69,  207,  202,   70,   71,   31,   46,   72,  208,   31,
      209,   73,   46,  204,  242,   74,  206,   31,   31,   31,

      210,   75,   31,  620,   76,  211,   46,   77,   31,   31,
       31,   78,  226,  224,  215,   79,  212,  225,   31,  213,
       31,   31,  214,   80,  217,   81,   31,  219,   46,   31,
       46,   82,   31,  221,  218,   88,   46,   31,  222,   89,
       31,  220,  223,   90,   31,   31,  231,   31,   31,   91,
       31,   46,   46,   92,   46,  239,  238,   93,   46,   31,
      243,   94,   31,   31,  230,   95,   31,   96,   31,   31,
      263,   46,   31,  235,   31,  287,  244,   46,   31,  245,
      240,   97,   46,   31,   46,   98,   31,   31,   31,  236,
      237,  252,  248,  246,  107,   99,  253,   31,   46,   31,

      249,  100,   31,  247,   31,  254,   31,  255,   31,   31,
      101,  264,  102,   46,  617,  103,   46,   46,  104,  105,
      106,  250,  107,  251,   31,  108,  109,  261,  259,  110,
       31,   31,  256,  111,   31,   31,   31,  112,  113,  257,
      114,  268,   31,  258,  115,  267,  262,   31,   46,   31,
      116,  117,  118,   31,   31,   46,  120,   46,  269,  265,
      121,   31,  255,   31,  122,  260,  255,   46,   31,   31,
      123,  255,  274,   31,   31,  266,  124,   31,  275,  272,
      125,   31,  270,   46,   31,  480,  271,  126,  127,  279,
      276,   31,   31,  128,  129,  273,   31,   31,  130,   31,

      131,   31,   46,   31,  132,  277,  133,   31,  290,   46,
       31,  134,  135,  289,  614,  280,  299,  288,  136,  278,
       31,   31,  137,  281,  138,   31,   46,   31,   31,  285,
       31,   46,  300,  291,  139,  140,  286,  292,   46,   31,
       46,  141,   31,  142,   31,  143,   31,   31,  301,  315,
      293,  306,   31,  144,   31,   31,  296,  145,  294,  295,
      302,   31,  297,  146,  298,   31,  147,  148,  303,  305,
       31,  149,  309,   31,  150,  151,  304,   31,   31,   31,
      255,  152,  308,  317,  311,  307,   31,  153,   46,   46,
      310,  611,  154,   31,   31,   31,  155,  318,  316,  319,

       31,  323,  156,   46,   31,   31,  320,   31,  157,   31,
      480,  321,  322,  326,  330,   31,  107,  187,   31,  188,
       46,  327,   31,  189,   31,  190,   31,  324,   46,  325,
      191,  192,  331,  333,   31,   31,  193,   31,  227,   31,
       31,  328,  329,   46,  332,  334,  335,   46,   31,   31,
       46,  228,   31,   31,   31,   31,  336,  229,  337,  338,
       31,   31,   46,   31,   31,   46,  255,   31,  339,   31,
      340,   46,  341,   46,   31,  343,   31,   31,  232,   31,
       31,   31,   31,  233,   31,  255,   31,  342,  384,   31,
       31,  234,   31,  348,  344,  282,  347,  346,  349,   31,

      351,  345,   46,  353,   31,  352,  350,   31,   31,  283,
       31,  354,  357,  358,  355,  284,   31,  356,   31,  312,
       31,   31,   31,  313,   31,   31,   31,   31,   31,   31,
       31,  359,  365,  314,  362,  364,  369,  363,  255,  361,
       31,  360,  368,   46,   31,   31,   46,  366,   31,   31,
       31,   31,  371,   31,  367,  372,   31,   31,  370,   31,
      375,   31,   31,   46,  255,   31,  377,  378,  379,   31,
       31,   46,   31,   31,   31,   31,   31,   31,  374,  376,
       46,   46,   31,   31,  381,   31,   31,   46,  389,   31,
       31,  387,  382,  388,  383,  385,   31,   31,   31,   31,

      255,  390,   31,  255,  386,  392,   31,   31,   31,   31,
       46,  255,   31,   31,   46,  396,   31,   31,   31,  393,
       31,   31,   31,   31,   31,  394,   31,  255,   31,  395,
       46,  255,   31,   31,   31,  255,   31,  397,   46,  255,
      401,  400,  402,   46,  403,  399,   31,   31,   31,   31,
       31,  404,   31,  407,   46,  255,   46,   46,  405,   46,
       31,   31,  408,   31,   31,   31,  406,  411,  255,   31,
       46,  409,   31,   31,   31,   31,  255,  410,   31,  413,
       31,   31,   31,  414,   31,   46,  255,  412,   31,   31,
       46,   31,   46,   31,   31,   31,   31,  423,   46,  421,

      417,  415,  420,  427,   31,  255,  419,   31,  418,  422,
       31,  424,   31,  425,   31,   31,   31,   31,  428,   31,
       31,   31,   31,   31,   31,  429,  255,   46,  606,   31,
       46,  255,  255,   31,  431,   31,  430,   46,  432,   31,
       46,   31,   46,   31,  433,  435,  436,   31,   31,   46,
       31,   46,   31,   46,  438,   31,  434,  437,   46,   31,
      440,   31,   31,   31,   31,  441,  439,   31,  442,   31,
       31,  255,  443,   31,   31,   31,   31,  255,   31,   31,
      255,   31,  444,  445,  449,  255,  447,   31,  448,   31,
      446,   31,   31,  450,  196,   31,  452,   31,  255,  451,

      453,   31,   31,   31,  457,   31,  456,  454,  455,   31,
       31,   31,  461,  458,   31,   31,  462,  459,  463,  460,
       31,   31,   31,   31,   31,  255,   31,  465,   31,   31,
      255,  464,   31,  467,  470,  468,   46,   31,   31,  469,
      472,  466,   31,   31,   31,   31,  471,   31,   31,   31,
       31,   31,   31,   31,   31,  476,   31,   31,   46,  477,
      473,  474,   31,  484,  478,  475,  479,   31,  481,  483,
      255,   31,   31,   31,  482,   46,  487,  491,   46,  485,
      486,   31,   31,   31,  489,  488,   46,   31,   31,   31,
      490,   31,   31,   31,   31,   31,  496,   31,   31,   31,

       31,   31,   31,   31,  497,  495,  494,   46,  492,   46,
      499,  255,  255,   46,   31,   46,   31,   31,   31,  498,
       31,   46,  500,  255,   31,   46,   31,   46,   46,   31,
       31,   31,  501,  255,   31,   31,   46,  502,   46,   31,
       31,   31,   31,  503,   31,   31,   31,   31,   31,  505,
      506,   31,   31,  513,   31,   46,   46,  504,  511,   31,
      255,  507,  510,   46,   31,  255,   31,  512,   46,   31,
      515,   31,  514,   31,  255,   31,  516,   31,  518,  520,
       31,   31,   46,  255,   31,   31,   31,   46,   31,  517,
       31,   31,   31,   31,   31,   31,   46,   31,   31,   31,

      255,  526,  255,   31,   31,  255,  521,  522,  525,   31,
      255,  523,  255,  524,  528,  255,   31,  527,   31,   31,
      532,  529,  255,   31,   46,  530,  531,   31,   31,  255,
       46,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,  255,  537,   31,  539,  533,  541,  535,
      536,  544,   46,  538,  534,   46,   31,  255,   31,  542,
       31,  543,   31,   31,   31,  540,   31,   31,   31,   31,
       31,   31,   31,  545,  546,   46,  548,  547,  255,   46,
       31,   31,   31,   31,  255,   31,  553,   31,  554,   31,
       46,   46,  552,   31,  550,   46,   46,   31,   31,   31,

       31,   31,  555,  557,   46,  556,   46,   46,  255,   31,
       31,  561,   31,   31,   31,  560,   31,  562,   31,   31,
       31,   31,   31,   46,   31,   31,   31,   31,  255,  567,
      255,  563,   46,  566,  255,  255,  564,   31,   31,   46,
       31,  255,   31,  255,   31,  255,   31,  255,  255,   31,
       31,   31,   31,  255,   31,  570,  255,   46,  255,   46,
      568,  255,  569,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,  572,  571,   46,  575,  574,   31,
      573,   31,  579,  581,   31,   31,  255,   31,  578,   31,
       31,  576,  577,   46,  583,  584,  586,  585,   31,   31,

       31,   31,   46,   31,   31,  587,  255,   46,  588,  589,
      590,   31,  255,   31,  107,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,  596,   31,  591,  255,   31,
       31,  594,  597,   46,   31,  593,   31,  595,   46,  604,
       46,  603,  598,  600,   31,  602,   31,   31,   31,   31,
       46,  255,   31,   31,   31,   31,  255,  609,  255,  607,
       31,   46,  605,   31,  608,   31,   31,   31,   31,  255,
       31,   31,  255,  615,  255,  255,   31,  610,   31,  616,
       31,   46,   31,   31,   31,   31,   31,   31,  612,  613,
      255,  621,   46,   31,  601,  618,  599,  623,  592,  619,

      255,  480,  255,  624,  480,   46,   32,   32,  480,  582,
      580,  565,  559,  558,  551,  549,  519,  480,  509,  508,
      480,   31,  480,  493,  480,  480,  426,  416,  398,   31,
      391,  380,  373,   31,   31,  216,   31,   31,   31,  625,
        3,  625,  625,  625,  625,  625,  625,  625,  625,  625,
      625,  625,  625,  625,  625,  625,  625,  625,  625,  625,
      625,  625,  625,  625,  625,  625,  625,  625,  625,  625,
      625,  625
    } ;

static const flex_int16_t yy_chk[1473] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,   88,   88,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        7,   15,   22,    7,   47,   14,   16,    7,   15,   16,
       14,   47,   30,  627,    7,   30,   33,    7,   57,   36,
        7,   14,   52,    7,   35,   22,   33,    7,    8,   30,
       37,   14,   34,   37,   57,   34,   36,   35,    8,    8,

       30,   36,   52,   39,   35,    8,   39,  622,    8,   34,
       37,    8,    9,   34,   38,   54,   40,   38,   42,    9,
       39,   38,   54,   40,   41,   39,   51,   40,   44,    9,
       41,   41,    9,   40,   45,    9,   10,   43,   42,   44,
       56,   42,   53,   10,   45,   10,   43,   48,   51,   50,
       44,   45,   50,   51,   43,   59,   10,   48,   55,   58,
       56,   60,   10,   11,   53,   55,   11,   48,   61,   62,
       58,  620,   62,   89,   11,   59,   63,   61,   65,   64,
       11,   65,   60,   11,   12,   66,   63,   12,   66,   67,
       66,   12,   64,   61,   89,   12,   63,   70,   77,   68,

       67,   12,   69,  617,   12,   68,   68,   12,   13,   74,
       76,   13,   77,   76,   70,   13,   69,   76,   72,   69,
       73,   75,   69,   13,   72,   13,   93,   73,   72,   81,
       76,   13,   17,   74,   72,   17,   93,   80,   75,   17,
       85,   73,   75,   17,   79,   83,   81,   90,   86,   17,
       18,   79,   80,   18,   81,   86,   85,   18,   83,   91,
       90,   18,   87,  109,   79,   18,   92,   18,   84,   95,
      109,   79,  128,   84,   99,  128,   91,   18,   19,   91,
       87,   19,   92,  100,   95,   19,   96,   94,   97,   84,
       84,   99,   96,   94,   99,   19,   99,   98,   97,  101,

       98,   19,   20,   94,  110,  100,  104,  101,  113,  106,
       20,  110,   20,   97,  614,   20,  113,   20,   20,   20,
       20,   98,   20,   98,  108,   20,   20,  106,  104,   20,
       21,  102,  102,   21,  114,  115,  103,   21,   21,  103,
       21,  114,  112,  103,   21,  112,  108,  105,  102,  116,
       21,   21,   21,   23,  111,  105,   23,  105,  115,  111,
       23,  117,  112,  118,   23,  105,  116,  112,  119,  121,
       23,  119,  121,  120,  124,  111,   23,   24,  121,  119,
       24,  122,  117,  120,  131,  611,  118,   24,   24,  124,
      122,  158,  130,   24,   24,  120,  123,  129,   24,  125,

       24,   25,  131,  137,   25,  123,   25,  132,  132,  158,
      138,   25,   25,  130,  606,  125,  137,  129,   25,  123,
      127,  133,   25,  125,   25,   26,  125,  151,  139,  127,
      134,  133,  138,  134,   26,   26,  127,  134,  139,  136,
       26,   26,  143,   26,  135,   26,   27,  140,  140,  151,
      134,  143,  142,   27,  141,  153,  136,   27,  135,  135,
      141,  146,  136,   27,  136,  144,   27,   28,  141,  142,
      149,   28,  146,  147,   28,   28,  141,  145,  152,  148,
      145,   28,  145,  153,  149,  144,  157,   28,   29,  148,
      147,  601,   29,  155,  154,  156,   29,  154,  152,  154,

      160,  157,   29,  152,  159,  162,  155,  164,   29,   49,
      599,  155,  156,  162,  164,  165,  154,   49,  163,   49,
      156,  163,  171,   49,  166,   49,  167,  159,  160,  159,
       49,   49,  165,  167,  168,  170,   49,   78,   78,  169,
      172,  163,  163,  171,  166,  168,  169,   78,  173,  174,
      170,   78,  176,  175,  177,  178,  172,   78,  173,  175,
      179,  180,   78,   82,  181,  174,  179,  185,  176,  182,
      177,  180,  178,   82,  183,  182,  184,  186,   82,  187,
      192,  189,  188,   82,  232,  185,  193,  181,  232,  191,
      194,   82,  126,  188,  183,  126,  187,  186,  189,  190,

      191,  184,  126,  193,  195,  192,  190,  198,  199,  126,
      197,  194,  198,  199,  195,  126,  150,  197,  200,  150,
      201,  202,  204,  150,  205,  203,  206,  208,  210,  207,
      211,  200,  208,  150,  203,  207,  211,  206,  204,  202,
      209,  201,  210,  150,  212,  213,  205,  209,  214,  215,
      217,  218,  213,  219,  209,  214,  220,  222,  212,  221,
      218,  223,  224,  222,  215,  225,  221,  224,  225,  226,
      228,  223,  229,  230,  231,  233,  234,  235,  217,  220,
      230,  219,  236,  237,  228,  238,  239,  226,  238,  242,
      240,  235,  229,  236,  231,  233,  243,  244,  246,  245,

      237,  240,  247,  243,  234,  245,  248,  249,  250,  251,
      244,  242,  253,  252,  239,  250,  257,  254,  258,  246,
      260,  262,  259,  261,  263,  247,  264,  249,  265,  248,
      252,  251,  268,  266,  270,  265,  272,  253,  254,  259,
      261,  260,  262,  257,  263,  258,  267,  269,  271,  273,
      275,  267,  276,  275,  264,  266,  270,  268,  272,  271,
      274,  278,  276,  279,  277,  280,  274,  279,  269,  281,
      273,  277,  282,  283,  284,  285,  281,  278,  286,  284,
      287,  288,  289,  286,  291,  285,  280,  282,  292,  293,
      283,  294,  289,  296,  298,  295,  302,  298,  287,  296,

      291,  288,  295,  302,  297,  294,  293,  303,  292,  297,
      299,  299,  300,  300,  304,  307,  305,  306,  303,  308,
      309,  310,  312,  311,  316,  304,  308,  306,  592,  317,
      316,  304,  305,  313,  309,  315,  307,  311,  310,  314,
      313,  318,  314,  319,  312,  315,  316,  320,  321,  313,
      323,  318,  324,  319,  320,  326,  314,  317,  313,  322,
      322,  325,  327,  328,  329,  323,  321,  330,  324,  331,
      334,  329,  325,  332,  333,  336,  337,  326,  338,  340,
      332,  335,  327,  330,  336,  328,  334,  339,  335,  341,
      331,  343,  342,  337,  333,  344,  339,  347,  343,  338,

      340,  345,  346,  348,  345,  349,  344,  341,  342,  350,
      351,  352,  350,  346,  354,  353,  351,  347,  352,  348,
      355,  356,  357,  361,  363,  357,  358,  355,  359,  362,
      349,  353,  360,  358,  361,  359,  354,  364,  365,  360,
      363,  356,  367,  366,  368,  369,  362,  370,  371,  375,
      372,  374,  378,  376,  377,  368,  379,  382,  364,  369,
      365,  366,  384,  378,  370,  367,  372,  387,  374,  376,
      377,  388,  381,  383,  375,  371,  383,  388,  379,  381,
      382,  385,  389,  386,  385,  384,  386,  390,  392,  393,
      387,  394,  395,  396,  397,  399,  399,  400,  401,  402,

      404,  406,  407,  408,  400,  397,  395,  404,  390,  389,
      402,  393,  394,  396,  405,  392,  409,  410,  411,  401,
      412,  405,  407,  410,  413,  408,  414,  412,  406,  415,
      417,  418,  411,  414,  419,  421,  409,  413,  418,  420,
      422,  423,  427,  417,  430,  428,  433,  438,  432,  421,
      422,  429,  431,  433,  434,  431,  415,  419,  428,  435,
      420,  423,  427,  432,  436,  429,  437,  430,  438,  441,
      435,  439,  434,  442,  436,  443,  435,  444,  439,  442,
      445,  448,  443,  444,  446,  447,  449,  448,  450,  437,
      451,  454,  452,  453,  455,  456,  441,  457,  458,  461,

      455,  456,  445,  459,  465,  446,  447,  449,  454,  466,
      459,  450,  451,  452,  458,  453,  460,  457,  462,  463,
      466,  461,  460,  464,  465,  462,  463,  467,  468,  464,
      466,  469,  470,  471,  472,  474,  473,  476,  475,  477,
      478,  479,  481,  472,  475,  483,  477,  467,  479,  471,
      473,  483,  469,  476,  470,  468,  484,  474,  482,  481,
      485,  482,  486,  487,  489,  478,  488,  494,  497,  492,
      490,  491,  495,  484,  485,  488,  490,  486,  491,  492,
      499,  498,  500,  502,  494,  503,  499,  513,  500,  501,
      487,  489,  498,  504,  495,  497,  501,  507,  505,  510,

      506,  511,  504,  507,  502,  505,  503,  506,  511,  512,
      514,  513,  515,  516,  517,  510,  518,  514,  520,  521,
      523,  524,  522,  518,  525,  527,  528,  526,  515,  523,
      512,  514,  517,  522,  526,  528,  516,  530,  529,  520,
      531,  521,  532,  524,  533,  525,  534,  527,  529,  536,
      535,  537,  538,  534,  539,  539,  531,  535,  530,  532,
      533,  538,  537,  540,  541,  542,  543,  544,  545,  546,
      547,  548,  552,  550,  540,  539,  536,  544,  542,  553,
      541,  556,  548,  550,  554,  557,  553,  555,  547,  560,
      564,  545,  546,  543,  552,  554,  560,  555,  561,  568,

      562,  563,  556,  566,  567,  561,  557,  562,  563,  566,
      568,  569,  564,  571,  567,  572,  573,  574,  575,  576,
      577,  583,  581,  578,  585,  575,  579,  569,  583,  584,
      587,  572,  577,  578,  588,  571,  586,  573,  574,  586,
      576,  585,  579,  581,  589,  584,  590,  591,  593,  594,
      587,  589,  595,  596,  597,  600,  591,  597,  594,  593,
      598,  588,  590,  602,  596,  603,  605,  604,  607,  598,
      608,  609,  602,  607,  595,  605,  610,  600,  612,  610,
      613,  609,  615,  616,  618,  619,  621,  623,  603,  604,
      613,  619,  608,  624,  582,  615,  580,  621,  570,  616,

      612,  565,  624,  623,  559,  618,  626,  626,  558,  551,
      549,  519,  509,  508,  496,  493,  440,  426,  425,  424,
      416,  403,  398,  391,  380,  373,  301,  290,  256,  255,
      241,  227,  216,  196,  107,   71,   46,   32,    5,    3,
      625,  625,  625,  625,  625,  625,  625,  625,  625,  625,
      625,  625,  625,  625,  625,  625,  625,  625,  625,  625,
      625,  625,  625,  625,  625,  625,  625,  625,  625,  625,
      625,  625
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[7] =
    {   0,
0, 0, 0, 0, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "187157-q6-symbol-table.l"
#line 2 "187157-q6-symbol-table.l"
    #include <iostream>
    #include <string>
    #include <unordered_map>
    #include <set>
    #include <utility>

    #define NONE            0
    #define CONJUCTION      1
    #define INTERJECTION    2
    #define PREPOSITION     3

    using namespace std; 

    typedef struct symbol_node{
        string name;
        int type;
    }symbol_node;

    typedef struct symbol_table{
        symbol_node symbol;
        struct symbol_table *next=NULL;    
    }symbol_table;
    
    symbol_table *H=NULL ,*T=NULL;

    //container of word frequency: [word : (count,[line numbers])]
    unordered_map<string, pair<int,set<int>>> frequency;

    void insert(char *match, int lineno, int type);
    void print();
#line 1025 "lex.yy.c"
#line 1026 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 40 "187157-q6-symbol-table.l"

#line 1245 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 626 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1441 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 41 "187157-q6-symbol-table.l"
{insert(yytext, yylineno, CONJUCTION);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 42 "187157-q6-symbol-table.l"
{insert(yytext, yylineno, INTERJECTION);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 43 "187157-q6-symbol-table.l"
{insert(yytext, yylineno, PREPOSITION);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 44 "187157-q6-symbol-table.l"
{insert(yytext, yylineno, NONE);}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 45 "187157-q6-symbol-table.l"
;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 46 "187157-q6-symbol-table.l"
ECHO;
	YY_BREAK
#line 1343 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 626 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 626 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 625);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 46 "187157-q6-symbol-table.l"


void insert(char *match, int lineno, int type){
    int ins = 0;
    string s = string(match);
    if(frequency.find(s)==frequency.end()){
        frequency[s] = pair<int,set<int>>();
        frequency[s].first = 1;
        ins=1;
    }else{
        frequency[s].first += 1;
    }
    frequency[s].second.insert(lineno);

    if(ins){
        if(type != NONE){
            if(H == NULL){
                H = new symbol_table();
                H->symbol.name = s;
                H->symbol.type = type;
                T=H;
            }else{
                T->next = new symbol_table();
                T = T->next;
                T->symbol.name = s;
                T->symbol.type = type;
            }
        }
    }
}

void print(){
    string type[] = {"","CONJUCTION","INTERJECTION","PREPOSITION"};
    cout<<"SYMBOL TABLE\n------------------------\n";
    cout<<"symbol\ttype\n------------------------\n";
    for(symbol_table *start = H; start!=NULL;start=start->next){
        cout<<start->symbol.name<<"\t"<<type[start->symbol.type]<<endl;
    }

    cout<<endl;
    cout<<"FRQUENCY TABLE\n--------------------------\n";
    cout<<"word\tcount\tlines\n-------------------------\n";
    for(auto entry:frequency){
        cout<<entry.first<<"\t"<<entry.second.first<<"\t";
        for(int ln:entry.second.second)
            cout<<ln<<",";
        cout<<"\b \n";
    }
}
int yywrap(){
    return 1;
}
int main(){
    yylex();
    print();
    return 1;
}

