#include <stdio.h>
/*

K_INTEGER K_UINTEGER K_BOOLEAN K_REAL K_IF K_ELSE K_SWITCH K_CASE K_DEFAULT K_WHILE K_FOR K_CONTINUE K_BREAK
O_ASSIGN O_ASSIGN_PLUS O_ASSIGN_MINUS O_ASSIGN_MUL O_ASSIGN_DIVIDE O_PLUS O_MINUS O_MUL O_DIVIDE O_EXP O_BOR O_BAND O_BNOT O_BXOR O_REQ O_RNEQ O_RLT O_RLEQ O_RGTH O_RGEQ O_UMINUS
N_ID
V_TRUE V_FLASE V_INTEGER V_REAL
*/

int main(){
    uint 
}